[build]
builder = "nixpacks"
buildCommand = """
curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
cd apps/server
pnpm install
pnpm run build
"""

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"